Models/ModelMetadataTypes/ProductMetadata.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.ModelMetadataTypes
{
    public class ProductMetadata
    {
        //[EmailAddress(ErrorMessage = "Lütfen doğru bir email adresi giriniz!!")]
        //[Required(ErrorMessage = "Lütfen email addresi giriniz")]
        //public string Email { get; set; }
        //[Required(ErrorMessage = "Lütfen product name'i giriniz")]
        //[StringLength(100, ErrorMessage = "Product name en fazla 100 karakter olabilir.")]s
        //public string Name { get; set; }
    }
}

Models/Product.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using WebApplication1.Models.ModelMetadataTypes;

namespace WebApplication1.Models
{
    public class Product
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
    }
}

Models/User.cs
namespace WebApplication1.Models
{
    public class User
    {
        public int Id { get; set; }
    }
}

Models/Validators/ProductValidator.cs
using FluentValidation;
using WebApplication1.Models;

namespace WebApplication1.Models.Validators
{
    public class ProductValidator : AbstractValidator<Product>
    {
        public ProductValidator()
        {
            RuleFor(x => x.Email).NotNull().WithMessage("Email bos olamaz!");
            RuleFor(x => x.Email).EmailAddress().WithMessage("Lütfen doğru bir email adresi giriniz.");
            RuleFor(x => x.Name).NotNull().WithMessage("Name bos olamaz!").NotEmpty().WithMessage("Name boş olmaz");
            RuleFor(x => x.Name).MaximumLength(100).WithMessage("Product name 100 karakteri gecemez!!!");
        }
    }
}

Models/ViewModels/UserProduct.cs
namespace WebApplication1.Models.ViewModels
{
    public class UserProduct
    {
        public Product Product { get; set; }
        public User User { get; set; }
    }
}

Areas/Fatura_Yönetimi/Controllers/AnasayfaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Areas.Fatura_Yönetimi.Controllers
{
    [Area("fatura_yönetimi")]
    public class AnasayfaController : Controller
    {
        public IActionResult Index()
        {
            var data = TempData["a"];
            return View();
        }
    }
}

Areas/Yönetim_Paneli/Controllers/AnasayfaController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Areas.Yönetim_Paneli.Controllers
{
    [Area("yönetim_paneli")]
    public class AnasayfaController : Controller
    {
        public IActionResult Index()
        {
            TempData["a"] = 12;
            return RedirectToAction("Index","Anasayfa", new { area = "fatura_yönetimi" });
        }
    }
}

Controllers/AnasayfaController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class AnasayfaController : Controller
    {
        ILog _log;
        public AnasayfaController(ILog log)
        {
            _log = log;
        }
        public IActionResult Anasayfa()
        {   
            _log.Log();
            return View();
        }
        public IActionResult HtmlBilgi()
        {
            return View();
        }
        public IActionResult Sayfa2()
        {
            return View();
        }

    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        #region  Json Result

        //public JsonResult GetProducts()
        //{
        //    JsonResult result = Json(new Product() { Id = 12 });
        //    return result;
        //}

        #endregion
        public IActionResult GetProducts()
        {
            //Veri üretilir.
            return View(); // => actiona ait view(.cshtml) dosyasını çağırır. 
        }
        #region ContentResult

        //public ContentResult GetProducts()
        //{
        //    ContentResult contentResult = Content("Gizli bir mesaj");
        //    return contentResult;
        //}

        #endregion

        public IActionResult Get()
        {
            var products = new List<Product>
            {
                new Product {Email = "" , Name  = "Tahiri", Quantity = 10},
                new Product {Email = "" , Name  = "Ahmet", Quantity = 20},
                new Product {Email = "" , Name  = "Sadık", Quantity = 1}
            };
            #region Model Bazlı Veri Gönderme
            //return View(products);
            #endregion
            #region ViewBag
            ViewBag.Products = products;
            #endregion
            #region ViewData
            ViewData["products"] = products;
            #endregion
            #region TempData
            TempData["products"] = products;
            #endregion
            return View();
        }
        public IActionResult GetTupple()
        {
            Product product = new Product { Email = "", Name = "Tahiri", Quantity = 19 };
            User user = new User { Id = 2 };
            //UserProduct userProduct = new();
            //userProduct.Product = product;
            //userProduct.User = user;
            //return View(userProduct);   

            var tuple = (product, user);
            return View(tuple);
             
        }
        public IActionResult CreateProduct()
        {
            //var headers = Request.Headers.ToList();
            //var routeValues = Request.RouteValues; 
            //var query = Request.QueryString;
            //var a = Request.Query["a"];
            //Tuple olarak nesene yakalama
            //var tuple = (new Product(),new User());
            return View();
        }
        //[HttpPost]
        //public IActionResult CreateProduct([Bind(Prefix ="Item1")]Product product,[Bind(Prefix ="Item2")]User user)
        //{
        //    return View();
        //}
        [HttpPost]
        public IActionResult CreateProduct(Product product)
        {
            //Kötü kod
            //if(!string.IsNullOrEmpty(product.Name) && product.Name.Length <= 100)
            //{
            //    //Veri tabanı işlemleri
            //    return View();
            //}

            //ModelState: Mvc de bir type'ın annotationslarının durumunu kontrol eden ve geriye sonuç dönen bir property.
            if (ModelState.IsValid) //Doğrulama yapıldıysa...
            {
                //Veri tabanı işlemleri
                return View();
            }
            else
            {
                //Loglama işlemleri ve kullanıcı bilgilendirmesi...
            }
            var messages = ModelState.ToList();
            return View(product);
        }
    }
}

ViewComponents/HakkımdaViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace WebApplication1.ViewComponents
{
    public class HakkımdaViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<string> bilgilerim = new List<string>();
            bilgilerim.Add("Tahiri");
            bilgilerim.Add("Web Developer");
            bilgilerim.Add("tahirifdn@gmail.com");
            return View(bilgilerim);
        }
    }
}

Views/Anasayfa/Anasayfa.cshtml
<html>
<head>
    <title>CSHTML İçinde CSS Kullanımı</title>
    <style>
        .centered-heading {
            text-align: center;
            color: blue;
        }
    </style>
</head>
<body>
    <div class="centered-heading">
        <h3>Web Eğitimleri Örnek Projesine Hoşgeldiniz!</h3>
    </div>
</body>
</html>

Views/Anasayfa/Components/Hakkımda/Default.cshtml
@model List<string>


<div class="submenu" id="submenu">
    <div class="submenu-content">
        <p class="submenu-title">Hakkımda</p>
        <p class="submenu-item">İsim: @Model[0]</p>
        <p class="submenu-item">Meslek: @Model[1]</p>
        <p class="submenu-item">E-posta: @Model[2]</p>
    </div>
</div>

Views/Anasayfa/HtmlBilgi.cshtml
@{
    Layout = null;
}

<html lang="tr-Tr">
<head>
    <!-- Veri hakkında bigi anlamına gelir meta!-->
    <meta charset="UTF-8" />
    <link href="~/Css/style.css" rel="stylesheet" />
    <title>HTML Hakkında</title>
</head>
<body>
    <header class="Ana-Başlık">
        <h1>📗 HTML OKUMA MATERYALİ</h1>
        <nav>
            <a class="Links" href="Anasayfa/Anasayfa.cshtml">Anasayfa</a>
            <a class="Links" href="#" target="_blank">Boş Link</a>
            <a class="Links" href="#">Flexbox</a>
            <a class="Links" href="#">CSS GRİD</a>
        </nav>
    </header>
    <article>
        <header>
            <!-- Her web sayfasında sadece bir tane h1 olabilir.!-->
            <!--alt : Bu chrome gibi araçların resimde ne olduğunu anlamasına yardımcı olur. Ayrıca görme engelli kişilerinde resmi anlayabilmesini sağlar.-->
            <h2 class="Başlık">
                Bir Web Etiketleme Dili Olan : <b id="HTML">HTML</b>
            </h2>
            <img src="~/ImageSource/Tokya-Ghoul-Profile.jpg"
                 alt="My Profile Picture"
                 height="75"
                 width="85" />
            <p id="Yazar">
                <strong>Tahiri Fidan</strong> tarafından çarşamba günü yazıldı, 9
                Ağustos 2023
            </p>

            <img src="~/ImageSource/post-img.jpg"
                 alt="HTML code içeren resim"
                 width="500"
                 height="200" />
        </header>

        <p>
            Tüm modern web siteleri ve web uygulamaları üç <em>temel</em> teknoloji
            kullanılarak oluşturulmuştur: HTML, CSS ve JavaScript. Bunlar web
            dilleridir.
        </p>

        <p>
            Bu yazıda, HTML'ye odaklanalım. HTML'nin neyle ilgili olduğunu ve sizin
            de neden öğrenmeniz gerektiğini öğreneceğiz.
        </p>
        <h3>HTML Nedir?</h3>
        <p>
            HTML, <strong>M</strong>etin <strong>İ</strong>şaretleme
            <strong>D</strong>ili anlamına gelir. Web geliştiricilerinin bir web
            sayfasının içeriğini yapılandırmak ve açıklamak için kullandıkları bir
            biçimlendirme dilidir (bir programlama dili değil).
        </p>
        <p>
            HTML, farklı içerik türlerini tanımlayan öğelerden oluşur: paragraflar,
            bağlantılar, başlıklar, resimler, video vb. Web tarayıcıları HTML'yi
            anlar ve HTML kodunu web siteleri olarak işler.
        </p>
        <p>HTML'de her öğe 3 bölümden oluşur:</p>
        <ol class="Üçlü">
            <!-- Ordered List => Sıralı Liste-->
            <li><em>Açılış etiketi</em></li>
            <!--List Item => Liste elemanı-->
            <li><em>Kapanış etiketi</em></li>
            <li><em>Asıl eleman</em></li>
        </ol>
        <!-- target : _blank parametresini laırsa linki tıkladığında açık olan sayfa kapanmıyacak onun yerine linki yeni sekmede açacaktır.-->
        <p>
            Daha fazla bilgi için
            <a href="https://developer.mozilla.org/en-US/docs/Web/HTML"
               target="_blank">MDN Web Docs.</a>
        </p>
        <h3>Neden HTML Öğrenmeliyim</h3>
        <p>
            Web'in temel dilini öğrenmek için sayısız neden var. İşte bunlardan 5
            tanesi:
        </p>
        <ul>
            <!-- UnOrdered List => Sırasız Liste-->
            <li>Temel web geliştirme dilini kullanabilmek</li>
            <li>
                Worpress veya Wix gibi araçlara güvenmek yerine güzel web sitelerini
                elle oluşturmak için
            </li>
            <li>Web uygulamaları oluşturmak için</li>
            <li>Arkadaşları etkilemek için</li>
            <li>Eğlenmek için 😃</li>
        </ul>
        <p class="Dilek-Mesajı">
            Umarız burada yeni bir şeyler öğrenmişsinizdir. Bir dahaki sefere
            görüşürüz!
        </p>
    </article>
    <!-- Kenar etiketidir. Ana bölümle doğrudan ilgisi olmayan ikincil bilgi içeren bölümdür-->
    <aside>
        <div>
            <h4>İlgili Makaleler</h4>
            <ul class="İlgili-Makaleler">
                <li>
                    <img src="~/ImageSource/related-1.jpg"
                         alt="Kod yazan adam"
                         height="75"
                         width="75" />&nbsp; <a href="adam.html">Kod yazan adam</a>
                    <h5 class="İlgili-Yazar"><em>By Ahmet Eldemir</em></h5>
                </li>
                <li>
                    <img src="~/ImageSource/related-2.jpg"
                         alt="Şimşek"
                         height="75"
                         width="75" />&nbsp;<a href="fırtına.html">Fırtınalar hakkında derin bilgiler</a>
                    <h5 class="İlgili-Yazar"><em>By Sadık Sünbül</em></h5>
                </li>
                <li>
                    <img src="~/ImageSource/related-3.jpg"
                         alt="Bir takım kodlar"
                         height="75"
                         width="75" />&nbsp;<a href="kod.html">Derinlemesine kod yazma sanatı</a>
                    <h5 class="İlgili-Yazar"><em>By Tahiri Fidan</em></h5>
                </li>
            </ul>
        </div>
    </aside>
    <!--Alt bilgi-->
    <footer>
        <p id="Copyright">Copyright &copy; 2023 by Via Team</p>
    </footer>
</body>
</html>

Views/Anasayfa/Partials/_subMenuPartial.cshtml
<style>
    .submenu {
        position: fixed;
        background-color: lightyellow;
        border: 1px solid #ddd;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        z-index: 1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 200px;
        padding: 10px;
        opacity: 0;
        transition: opacity 0.3s ease, transform 0.3s ease;
    }

        .submenu.active {
            opacity: 1;
            transform: translate(-50%, -50%) scale(1);
        }

    .submenu-content {
        padding: 10px;
    }

    .submenu-title {
        font-weight: bold;
        margin-bottom: 10px;
    }

    .submenu-item {
        margin-bottom: 5px;
    }
</style>

<div class="lower-menu">
    <a href="#" onclick="toggleSubmenu()">Hakkımda</a>
    <a href="#" onclick="toggleSubmenu()">İletişim</a>
</div>

<script>
    function toggleSubmenu() {
        var submenu = document.getElementById("submenu");
        submenu.classList.toggle("active");
    }
</script>

Views/Anasayfa/Sayfa1.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
Bu bir sayfa1dir.

Views/Anasayfa/Sayfa2.cshtml
<!DOCTYPE html>
<!-- bildirimi, belgenin bir <span style="color: green;">HTML5</span> belgesi olduğunu tanımlar. -->

<html>
<!-- etiketi, bir <span style="color: green;">HTML</span> sayfasının kök elementidir. -->

<head>
    <!-- etiketi, <span style="color: green;">HTML</span> sayfası hakkında <span style="color: blue;">meta</span> bilgileri içerir. -->

    <title>
        <!-- etiketi, <span style="color: green;">HTML</span> sayfası için bir başlık belirtir (bu başlık tarayıcının başlık çubuğunda veya sayfanın sekmesinde görüntülenir). -->
        HTML Etiketleri
    </title>

</head>

<body style="background-color:powderblue">
    <!-- etiketi, belgenin gövdesini tanımlar ve başlıklar, paragraflar, resimler, bağlantılar, tablolar, listeler vb. gibi tüm görünür içerikler için bir konteyner görevi görür. -->

    <h1>
        <!-- etiketi, büyük bir başlık tanımlar. -->
        HTML Etiketleri Hakkında Bilgi
    </h1>

    <p>
        <!-- etiketi, bir paragraf tanımlar. -->
        HTML etiketleri, HTML belgelerindeki yapıyı ve anlamı belirtmek için kullanılır.
        Etiketler, açılış ve kapanış etiketleri arasına yerleştirilen içerikten oluşur.
        Bazı etiketler ise kendi kendine kapanan etiketlerdir ve sadece açılış etiketi içerir.
        Etiketlerin bazıları zorunlu iken bazıları isteğe bağlıdır.
        Etiketlerin büyük küçük harf duyarlılığı yoktur ancak küçük harf kullanmak iyi bir uygulamadır.
    </p>
    <p>HTML bağlantıları, <a> etiketi ile tanımlanır.</p>
    <p><a> etiketinin en önemli özelliği href özelliğidir. Bu özellik, bağlantının gideceği yeri belirtir.</p>
    <p>Açılış <a> etiketi ile kapanış </a> etiketi arasındaki metin, bağlantı metnidir. Bu metin, kullanıcıya bağlantının nereye gittiğini gösterir.</p>
    <p>Örnek: <a href="https://www.w3schools.com">w3schools</a></p>
    <p>Bu örnekte, href özelliği https://www.w3schools.com adresini belirtir. Bu adres, W3Schools adlı bir web sitesidir. Bağlantı metni ise "Bu bir bağlantıdır" şeklindedir. Bu metin, kullanıcıya tıklayınca W3Schools sitesine gideceğini söyler.</p>
    <h1>HTML Resimleri Hakkında Bilgi</h1>
    <p>HTML resimleri, <img> etiketi ile tanımlanır.</p>
    <p><img> etiketinin kaynak dosyası (src), alternatif metin (alt), genişlik (width) ve yükseklik (height) gibi özellikleri vardır.</p>
    <p>Örnek: <img src="https://www.w3schools.com/images/img_girl.jpg" alt="W3Schools.com" width="104" height="142"></p>
    <p>Bu örnekte, src özelliği w3schools.jpg dosyasını belirtir. Bu dosya, W3Schools sitesinin logosudur. alt özelliği ise "W3Schools.com" şeklindedir. Bu metin, resim görüntülenemediği durumlarda veya görme engelli kullanıcılar için kullanılır. width ve height özellikleri ise resmin genişliğini ve yüksekliğini piksel cinsinden belirtir.</p>
    <h1>HTML Style Özelliği Hakkında Bilgi</h1>
    <p>style özelliği, bir elemente renk, font, boyut gibi stiller eklemek için kullanılır.</p>
    <p>Örnek:
    <p style="color:red;">Bu bir kırmızı paragraftır.</p></p>
    <p>Bu örnekte, style özelliği ile paragrafın rengi kırmızı olarak belirlenmiştir. style özelliği içinde CSS kuralları yazılır. CSS, web sayfalarının görünümünü biçimlendirmek için kullanılan bir dilidir.</p>
    <p>style özelliği ile bir elemente birden fazla stil uygulamak mümkündür. Örneğin, aşağıdaki kodda paragrafın rengi, fontu ve boyutu değiştirilmiştir.</p>
    <p>Örnek:
    <p style="color:blue; font-family:Arial; font-size:20px;">Bu bir mavi paragraftır.</p></p>
    <h1>HTML Title Attribute Hakkında Bilgi</h1>
    <h2 title="Ben bir başlığım">The title Attribute</h2>
    <p title="Ben bir ipucuyum">Mouse'yi paragrafın üstüne getirerek ipucunu okuyabilirsiniz.</p>
    <h1>Başlık 1</h1>
    <p>Bu bir textir.</p>
    <hr> <!-- Görüldüğü üzere bir çizgi ile satırları ayırır.-->
    <h2>Başlık 2</h2>
    <p>Buda başka bir textir.</p>
    <hr>
    <pre> <!-- pre etiketi içerisnde yazılı olan metnin satırları ve bırakılan boşlukları koruyacak şekilde yapılanır. Görüntüler...-->
    My Bonnie lies over the ocean.

    My Bonnie lies over the sea.

    My Bonnie lies over the ocean.

    Oh, bring back my Bonnie to me.
    </pre>
    <p><mark>Süt</mark> almayı unutma!</p>
    <p>My favorite color is <del>blue</del> red.</p>
    <p>My favorite color is <del>blue</del> <ins>red</ins>.</p>
    <p>This is <sub>subscripted</sub> text.</p>
    <p>This is <sup>superscripted</sup> text.</p>
</body>

</html>

Views/Product/CreateProduct.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model WebApplication1.Models.Product

<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @*<form asp-action="CreateProduct" method="post">
    <input type ="number" asp-for="Item1.Name" placeholder="Product Id"/>
    <br />
    <input type ="text" asp-for="Item2.Id" placeholder="Product Name"/>
    <br />
    <button>Ürün Ekle</button>
    </form>*@
    <form asp-action="CreateProduct" asp-controller="Product" method="post">
        <input type="email" asp-for="Email" placeholder="Product Id" /> <span asp-validation-for="Email"></span>
        <br />
        <input type="text" asp-for="Name" placeholder="Product Name" /> <span asp-validation-for="Name"></span>
        <br />
        <input type="text" asp-for="Quantity" placeholder="Product Quantity" />
        <br />
        <button>Ürün Ekle</button>
    </form>

Views/Product/Get.cshtml
@*model List<WebApplication1.Models.Product>
<ul>
    @foreach(var product in Model)
    {
        <li>@product.Name</li>
    }
</ul>*@
<h1>ViewBag</h1>
<ul>
    @foreach (var product in ViewBag.Products as List<WebApplication1.Models.Product>)
    {
        <li>@product.Name</li>
    }
</ul>
<h2>ViewData</h2>
<ul>
    @foreach (var product in ViewData["products"] as List<WebApplication1.Models.Product>)
    {
        <li>@product.Name</li>
    }
</ul>
<h3>TempData</h3>
<ul>
    @foreach (var product in TempData["products"] as List<WebApplication1.Models.Product>)
    {
        <li>@product.Name</li>
    }
</ul>
@*Burada html helper kullanarak farklı bir view'i view içinde render edebiliyoruz. Ayrıca Bu viewi çağıran action metot üzerinden de gelen modeller bu sayfaya diekt olarak gitmektedir.*@
@Html.Partial("~/Views/Product/Partials/ListPartial.cshtml")

Views/Product/GetProducts.cshtml
@*@using WebApplication1.Extensions

@Html.TextBox("txtadi",null,new { style  = "background-color:green; color: white"})

@Html.CustomTextBox("txtcustomadi",null,"Adınız")*@
<!-- Burada belirtilen sınıftan tag helperları çekiyoruz.-->
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, WebApplication1
@*<form asp-action="GetProducts",asp-controller="Product"method="post">

    <input type/>
    <select>
        <option></option>
    </select>

</form>*@
@*<cache>
    Cache : @DateTime.Now
</cache>
<br />
@DateTime.Now*@
<email mail = "tahirifdn@gmail.com" display="Tahiri'nin maili'"></email>

Views/Product/GetTupple.cshtml
@*@model WebApplication1.Models.ViewModels.UserProduct
<h3>@Model.Product.Name</h3>
<h3>@Model.User.Id</h3>*@

@model (WebApplication1.Models.Product,WebApplication1.Models.User)

<h3>@Model.Item1.Name</h3>
<h3>@Model.Item2.Id</h3>

Views/Product/Partials/ListPartial.cshtml
<h1>@ViewBag.Products[0].Name</h1>

Views/Shared/_Layout.cshtml
<!-- Bu view layout yapılanması içerir. Yani ortak render edilen görüntü kodları burada yazılacaktır.-->
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Üst ve Alt Menü Tasarımı</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }

        .upper-menu {
            background-color: #444;
            display: flex;
            justify-content: center;
            padding: 5px;
        }

            .upper-menu a {
                color: #fff;
                text-decoration: none;
                margin: 0 10px;
            }

        .lower-menu {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: #444;
            text-align: center;
            padding: 5px;
        }

            .lower-menu a {
                color: #fff;
                text-decoration: none;
                margin: 0 10px;
            }
    </style>
</head>
<body>
    <header>
        <h1>Üst Menü Tasarımı</h1>
    </header>
    <div class="upper-menu">
        <a href="/Anasayfa/Anasayfa">Anasayfa</a>
        <a href="/Anasayfa/HtmlBilgi">HtmlBilgi</a>
        <a href="/Anasayfa/Sayfa2">Sayfa 2</a>
    </div>

    @await Component.InvokeAsync("Hakkımda") 
    <partial name="~/Views/Anasayfa/Partials/_subMenuPartial.cshtml" />
    <div>
        @RenderBody()
    </div>

    
</body>
</html>